"""add conversation and push subscription delete cascade

Revision ID: 0130e4cadfcc
Revises: c30d7f7e965c
Create Date: 2026-06-14 13:10:55.552963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0130e4cadfcc'
down_revision = 'c30d7f7e965c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_participants_staff_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_participants_super_admin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'super_admins', ['super_admin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('push_subscriptions_super_admin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('push_subscriptions_staff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'super_admins', ['super_admin_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('push_subscriptions_staff_id_fkey'), 'staff', ['staff_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('push_subscriptions_super_admin_id_fkey'), 'super_admins', ['super_admin_id'], ['id'])

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_participants_super_admin_id_fkey'), 'super_admins', ['super_admin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_participants_staff_id_fkey'), 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###
