"""Update staff and task delete cascade constraints

Revision ID: c30d7f7e965c
Revises: fa63f3f73210
Create Date: 2026-06-14 12:16:32.562901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30d7f7e965c'
down_revision = 'fa63f3f73210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_department_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('staff_department_assignments_department_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('staff_department_assignments_staff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_department_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_department_assignments_department_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('task_department_assignments_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_staff_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_staff_assignments_task_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('task_staff_assignments_staff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_by_staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('tasks_created_by_staff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['created_by_staff_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tasks_created_by_staff_id_fkey'), 'staff', ['created_by_staff_id'], ['id'])
        batch_op.alter_column('created_by_staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task_staff_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_staff_assignments_staff_id_fkey'), 'staff', ['staff_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('task_staff_assignments_task_id_fkey'), 'tasks', ['task_id'], ['id'])

    with op.batch_alter_table('task_department_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_department_assignments_task_id_fkey'), 'tasks', ['task_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('task_department_assignments_department_id_fkey'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('staff_department_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('staff_department_assignments_staff_id_fkey'), 'staff', ['staff_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('staff_department_assignments_department_id_fkey'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###
