"""Add calendar events table

Revision ID: fa63f3f73210
Revises: 
Create Date: 2026-06-14 01:23:14.496970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa63f3f73210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'board_tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'board_tasks', ['dependency_task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_staff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_staff_id_fkey'), 'staff', ['staff_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('board_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
